### ISSUE TITLE
The ivy package has been updated and some functions referred has been changed

### ISSUE THREAD

**Issue by Gilbert-Wong** [s-kostyaev/ivy-erlang-complete#10]
Hi, s-kostyaev. 

Look at this link :[https://github.com/abo-abo/swiper/commit/93d51d6188956da2592c1458b68d7cef48d967ae](https://github.com/abo-abo/swiper/commit/93d51d6188956da2592c1458b68d7cef48d967ae)

There is a new function `ivy-alist-setting` and the parameters in `counsel-more-chars` has been changed. I supposed that `ivy-erlang-complete` need to update to adapt the latest ivy package.

**Comment by Gilbert-Wong** [comment]
I have pulled request it. Please review it and merge into master branch.

**Comment by s-kostyaev** [comment]
Merged. Thank you.
