### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by ksallberg** [s-kostyaev/ivy-erlang-complete#17]
Hello, I am interested in trying out ivy-erlang-complete because I would like a more light weight alternative to EDTS.

The project that I work on, is not rebar or rebar3 based. And it is a very large erlang project. When I try to do 'ivy-erlang-complete-find-definition', emacs just hangs. No new emacs windows or anything are opened AFAICS.

Do you have any suggestions on how to debug?

**Comment by s-kostyaev** [comment]
Try to create `.dir-locals.el` in project root with content:
```elisp
((erlang-mode . ((ivy-erlang-complete-project-root . (expand-file-name ".")))))
```

**Comment by s-kostyaev** [comment]
With rebar this project try to set project root automatically. Without rebar you can set it manually.

**Comment by ksallberg** [comment]
Hmm... I have tried (at home, with macos) with a project that uses rebar3. No such file (.dir-locals.el) is created when i do 'rebar compile'. 

The completion seems to find the actual function definition I am looking for, but it also complains that it did not find "/usr/lib/erlang", which I don'h have since I use macos and homebrew.

https://github.com/login?return_to=%2Fs-kostyaev%2Fivy-erlang-complete%2Fissues%2F17

**Comment by ksallberg** [comment]
Ok! I read your emacs lisp and tried setting ivy-erlang-complete-erlang-root. And now it seems to work on my home computer. I will try on my work linux machine this week.

```
(require 'ivy-erlang-complete)
(add-hook 'erlang-mode-hook #'ivy-erlang-complete-init)
;; automatic update completion data after save
(add-hook 'after-save-hook #'ivy-erlang-complete-reparse)

(setq ivy-erlang-complete-erlang-root "/usr/local/Cellar/erlang/21.3.2")
```

**Comment by s-kostyaev** [comment]
> Or should rebar3 just have created a correct '.dir-locals.el' for me, but did not?

No it shouldn't. `ivy-erlang-complete` use rebar config path to predict project root.

> Do you think the README file of this project should say something about ivy-erlang-complete-erlang-root?

Good idea.

**Comment by ksallberg** [comment]
I tried creating .dir-locals.el in project root, and also tried setting 'ivy-erlang-complete-erlang-root'. But if I try to use ivy-erlang-complete or ivy-erlang-complete-find-definition, emacs just freezes. And nothing is written to *Messages*, so I'm having trouble figuring out what is happening. Any ideas?

**Comment by ksallberg** [comment]
Trying at work: I tried creating .dir-locals.el in project root, and also tried setting 'ivy-erlang-complete-erlang-root'. But if I try to use ivy-erlang-complete or ivy-erlang-complete-find-definition, emacs just freezes. And nothing is written to Messages, so I'm having trouble figuring out what is happening. Any ideas?

**Comment by s-kostyaev** [comment]
Try `M-x` `toggle-debug-on-quit` and `toggle-debug-on-quit` before start. And when emacs will be freezed press `C-g` (maybe multiple times). And paste debugger output here.

**Comment by ksallberg** [comment]
Then a backtrace window appeared, with this:
```
Debugger entered--Lisp error: (quit)
  re-search-backward("??#?['A-Za-z0-9_:]*" nil t)
  thing-at-point-looking-at("??#?['A-Za-z0-9_:]*")
  ivy-erlang-complete-thing-at-point()
  ivy-erlang-complete-find-definition()
  call-interactively(ivy-erlang-complete-find-definition nil nil)
  command-execute(ivy-erlang-complete-find-definition)
```

**Comment by s-kostyaev** [comment]
Looks strange. Which file size you tested at?

Also `C-h v` `ivy-erlang-complete-erlang-root` and `C-h v` `ivy-erlang-complete-project-root` is paths that you set up?

**Comment by ksallberg** [comment]
Yes I set these in my .emacs file.

Individual erlang file size is small, none larger than 20k lines. A couple of hundred of these maybe. But there are several gigabytes of other files (not .erl) in the repo.

EDTS works just fine, except that it tends to break with each new Erlang/OTP release and it is getting cumbersome.

```
C-h v ivy-erlang-complete-erlang-root:
ivy-erlang-complete-erlang-root is a variable defined in `ivy-erlang-complete.el'.
Its value is "/home/krisallb/Documents/stash/annan/otp"
Original value was "/usr/lib/erlang/"

Documentation:
Path to erlang root.

You can customize this variable.
```

```
C-h v ivy-erlang-complete-project-root:

ivy-erlang-complete-project-root is a variable defined in `ivy-erlang-complete.el'.
Its value is "/home/krisallb/Documents/stash/annan"

Documentation:
Path to erlang project root.
```

**Comment by s-kostyaev** [comment]
Your erlang root inside your project?

Did you try LSP for that? With `lsp-mode` or `eglot`? Currently I don't use erlang, but prefer LSP for my golang development.

**Comment by s-kostyaev** [comment]
> But there are several gigabytes of other files (not .erl) in the repo.

I think that can be the root of the problem. This project is pretty dumb and makes search in files and sometimes it's sync operation. So you can wait blocked for a long time during io. I think you should prefer more intelligent utilities for that project like LSP server. EDTS can stay broken several months after new OTP release. It was one of reasons to create this project. Also you can try abandoned `distel`. It can still work. But try LSP first)

**Comment by ksallberg** [comment]
Yes the erlang root is inside the project, that is what the system I work on looks like. Thanks for the pointer, I will try out LSP!

**Comment by ksallberg** [comment]
Hey! Wait a sec

I used emacs-24 when I experienced the hang. Now I installed emacs-25 in order to be able to try LSP. But I forgot to remove the ivy-erlang-complete startup calls from my .emacs file. And in emacs-25 it just works. No more hanging.

**Comment by ksallberg** [comment]
Hey! Wait a sec

I used emacs-24 when I experienced the hang. Now I installed emacs-25 in order to be able to try LSP. But I forgot to remove the ivy-erlang-complete startup calls from my .emacs file. And in emacs-25 ivy-erlang-complete just works. No more hanging.

Maybe add a note in the README to warn about emacs-24, if you know/suspect this is the case?

**Comment by s-kostyaev** [comment]
It's strange) I prefer update `ivy-erlang-complete` requirements instead of README then. Thanks for information.

**Comment by s-kostyaev** [comment]
I think you could try LSP anyway)
