### ISSUE TITLE
There something wrong when i use ` (ivy-erlang-complete-find-definition)`.

### ISSUE THREAD

**Issue by erow** [s-kostyaev/ivy-erlang-complete#3]
> ELISP>(ivy-erlang-complete-find-definition)
"error code 127"

I have tried to read the code. but i know nothing ablout ivy.
`(ivy-erlang-complete-thing-at-point) `  return "io:format"

**Comment by s-kostyaev** [comment]
Do you have installed `the_silver_searcher`?

**Comment by s-kostyaev** [comment]
Also for functions from erlang standart library use `ivy-erlang-complete-show-doc-at-point` instead of `ivy-erlang-complete-find-definition`

**Comment by s-kostyaev** [comment]
> I have tried to read the code. but i know nothing ablout ivy.

http://oremacs.com/swiper/

**Comment by erow** [comment]
aha！I got it! function `counsel-ag` need linux command `ag` and i fixed it.I like  the swiper search.But i cann't find the history command.Please tell me how to show the history commands.

**Comment by s-kostyaev** [comment]
`the_silver_searcher` is linux package with binary `ag`.
> Please tell me how to show the history commands.

I don't understand what history you need. Add example please. If you need history of `M-x` commands install also `smex` package.

**Comment by erow** [comment]
The `ivy-read` API has an argument `:history` .And it will record what i enter. But i cann't find an command to see it or how to use it.

**Comment by s-kostyaev** [comment]
In `ivy-minibuffer-map` I was found this:
```elisp
    (define-key map (kbd "M-n") 'ivy-next-history-element)
    (define-key map (kbd "M-p") 'ivy-previous-history-element)
```
Is this answer your question?

**Comment by s-kostyaev** [comment]
@erow I close this issue. If you have this problem for now let me know.
