### ISSUE TITLE
Have some problems on ivy-erlang-complete

### ISSUE THREAD

**Issue by Gilbert-Wong** [s-kostyaev/ivy-erlang-complete#9]
When I type the `io:for` and try to use `ivy-erlang-complete`  autocomplete the function.  It returns`    io:sed: 1: "/-export(\[.*\\])./{ n  ...": extra characters at the end of d command` . It don't know how to solve it . Can you give me some help?

**Comment by Gilbert-Wong** [comment]
I  use `homebrew` to install `erlang` on my mac.This is my erlang path `/usr/local/Cellar/erlang/20.2.4/lib/erlang/`  It seems there's some problem in `exported-funcs.sh` or `exported-types.sh`. I don't know what happens on  `sed` command

**Comment by Gilbert-Wong** [comment]
I found that when I use `ivy-erlang-complte-show-doc-at-point`, it doens't work.

![image](https://user-images.githubusercontent.com/20479699/37237685-d5887d9c-2451-11e8-845c-8c300baf3be6.png)

![image](https://user-images.githubusercontent.com/20479699/37237676-be50aafa-2451-11e8-9751-fca14ceb2ba4.png)

**Comment by s-kostyaev** [comment]
Try to customize 'ivy-erlang-complete-erlang-root' and set it  '/usr/local/Cellar/erlang/20.2.4/lib/erlang/'

**Comment by Gilbert-Wong** [comment]
I tried it , but it still doesn't auto complete correctly, this is my config:
```elisp
(defun gilbert-programming/init-ivy-erlang-complete()
  "Setup for erlang."
  (use-package ivy-erlang-complete
    :defer t
    :ensure t
    :init
    (add-hook 'erlang-mode-hook #'ivy-erlang-complete-init)
    ;; automatic update completion data after save
    (add-hook 'after-save-hook #'ivy-erlang-complete-reparse)
    (add-to-list 'auto-mode-alist '("rebar\\.config$" . erlang-mode))
    (add-to-list 'auto-mode-alist '("relx\\.config$" . erlang-mode))
    (add-to-list 'auto-mode-alist '("system\\.config$" . erlang-mode))
    (add-to-list 'auto-mode-alist '("\\.app\\.src$" . erlang-mode))
    :custom
    (ivy-erlang-complete-erlang-root "/usr/local/Cellar/erlang/20.2.4/lib/erlang")
    )
  )

```

**Comment by Gilbert-Wong** [comment]
But 
But the function `ivy-erlang-complete-find-definition` does work.
![image](https://user-images.githubusercontent.com/20479699/37250056-c2991efc-252e-11e8-94d2-bafb41b02358.png)

**Comment by s-kostyaev** [comment]
@Gilbert-Wong thanks for reporting

**Comment by Gilbert-Wong** [comment]
After you fixed sed behavior yesterday. The problem still exists. And I still cannot complete erlang code correctly.

**Comment by s-kostyaev** [comment]
> The problem still exists.

Which version do you use?

**Comment by Gilbert-Wong** [comment]
The latest version.

**Comment by s-kostyaev** [comment]
Did you restart emacs after update? Please show new screenshots.

**Comment by Gilbert-Wong** [comment]
Of course.
![image](https://user-images.githubusercontent.com/20479699/37266382-c0c9fd50-25f4-11e8-9b6d-4e4203cd42de.png)

![image](https://user-images.githubusercontent.com/20479699/37266393-cd9f9be8-25f4-11e8-8606-8a4ff842c302.png)
![image](https://user-images.githubusercontent.com/20479699/37266415-dd22603c-25f4-11e8-8acc-f293d5f81366.png)

**Comment by s-kostyaev** [comment]
can you try to install `gnu sed`? And make it default sed in `$PATH` for test. I don't have mac, but I think that it can be result of differences between gnu sed & bsd sed. If that thrue I can install freebsd into virtualbox but not next weekend.Maybe after two weeks.

**Comment by Gilbert-Wong** [comment]
Yeah . I have replaced `bsd-sed` to `gnu-sed` . It works now!  Thank you for your help very much.
